name: ds2
channels:
  - conda-forge
dependencies:
  # You need the pangeo-notebook conda-forge package in your environment.yml for compatibility with pangeo cloud deployments
#  - pangeo-notebook==2024.02.02
  # The rest of the packages are up to you!
  - xarray
  - hvplot
  - gcsfs
  - intake
  - intake-xarray
  - zarr
  - cartopy
  - scikit-learn
  - seaborn
  - dask-ml
  - graphviz
  - coiled
  - google-cloud-sdk
  - ipykernel
  - argopy
  - s3fs
  - xarrayutils
  - copernicusmarine
  - gsw

  - pip
  - pip:
    - httpimport
    - coiled[notebook]
    - pyopenssl==24.3.0
